### ISSUE TITLE
Another TTGO esp32camera module

### ISSUE THREAD

**Issue by drmocm** [geeksville/TenDollarWebcam#1]
https://www.aliexpress.com/item/TTGO-T-Camera-ESP32-WROVER-PSRAM-Camera-Module-ESP32-WROVER-B-OV2640-Camera-Module-0-96/32968683765.html

**Comment by drmocm** [comment]
Sorry the paste triggered the comment.
The camera can be found here:
https://www.aliexpress.com/item/TTGO-T-Camera-ESP32-WROVER-PSRAM-Camera-Module-ESP32-WROVER-B-OV2640-Camera-Module-0-96/32968683765.html

and works with 
#define I2C_SDA 21
#define I2C_SCL 22

in src/ESP32-devcam.ino 

and 

camera_config_t esp32cam_config {

    .pin_pwdn = 26,
    .pin_reset = -1,

    .pin_xclk = 32,

    .pin_sscb_sda = 13,
    .pin_sscb_scl = 12,

    .pin_d7 = 39,
    .pin_d6 = 36,
    .pin_d5 = 23,
    .pin_d4 = 18,
    .pin_d3 = 15,
    .pin_d2 = 4,
    .pin_d1 = 14,
    .pin_d0 = 5,
    .pin_vsync = 27,
    .pin_href = 25,
    .pin_pclk = 19,
    .xclk_freq_hz = 20000000,
    .ledc_timer = LEDC_TIMER_0,
    .ledc_channel = LEDC_CHANNEL_0,
    .pixel_format = PIXFORMAT_JPEG,
    .frame_size = FRAMESIZE_SVGA,
    .jpeg_quality = 12, //0-63 lower numbers are higher quality
    .fb_count = 2 // if more than one i2s runs in continous mode.  Use only with jpeg
};

in .piolibdeps/Micro-RTSP_ID6071/src/OV2640.cpp

**Comment by geeksville** [comment]
ooh thanks.  I'll add an ifdef.  Was the only difference the two I2C pins or did you have to change any of the others?

**Comment by drmocm** [comment]
esp32cam_config also needs to be changed. The camera uses different pins. I used the description on the aliexpress page of the camera.

**Comment by drmocm** [comment]
[ttgo.txt](https://github.com/geeksville/TenDollarWebcam/files/2833499/ttgo.txt)

I needed to add the  esp32cam_ttgo_t_config structure in order for the TTGO-T to work. I don't know much about Platformio, so that was the only way to fix it for me right now
The diff is attached. Haven't done much with git, so did not want to experiment with forks and pull requests.

**Comment by geeksville** [comment]
Thanks I added your new version of the structure to the lib.
