### ISSUE TITLE
is this a hardware issue (image attached)

### ISSUE THREAD

**Issue by matphillips** [geeksville/TenDollarWebcam#10]
I have two boards, one the ESP32-CAM (no usb) and one M5Stack (USB C) types.

The M5Stack board is giving a bad image, with green blobs visible all over the image, as per the capture attached. The other board is fine. Is this likely to be a hardware issue, or could it be something wrong in the code or my settings?

Thanks.

![capture](https://user-images.githubusercontent.com/1055525/53355269-8f742100-3920-11e9-9750-30a939874af0.jpg)

**Comment by keyfour** [comment]
It looks like some noise. I had problems with ESP32-CAM image because of noises in power rails. It was horizontal stripes on images. Better ground and bypass capacitors helps. I'm not pretty sure that it will be useful for you one year apart, but maybe it will be useful for someone with similar problems.

**Comment by matphillips** [comment]
Thanks for the message @keyfour , if I find the board (it's around here somewhere I'm sure) I may try adding a decent cap to the power lines but if I remember the issue correctly, that green pattern was absolutely static on the screen. If it was noise, I'd expect it to stutter and shake around some. Could be noise that's somehow linked to the clock signal, which could lock it to the display perhaps? 

Either way, I think it sure must have been hardware in some way, and not an issue with the software. I had forgotten all about this to be honest! I'll go ahead and close the issue :)
