### ISSUE TITLE
AutoWifi Vs AutoConnect

### ISSUE THREAD

**Issue by dkvinyls** [geeksville/TenDollarWebcam#11]
Any chance you could incorporate AutoConnect into this project? I tried but I'm out of my depth.

I can't find an android app that supports SmartConfig that will work with Android 9, they all come up with <unknown ssid>, I beleive there was a change in Android 9 that affects an apps permission to wifi details which requires location permissions and none of the apps request location.

**Comment by dkvinyls** [comment]
Nevermind, smartconfig does work it's just very hit and miss.

**Comment by mxr0** [comment]
I would also love to see AutoConnect. if it is possible and does fit the space constraint.
