### ISSUE TITLE
Wifi provisioning not working and local Micro-RTSP

### ISSUE THREAD

**Issue by bbbenji** [geeksville/TenDollarWebcam#4]
In the last commit looks like you kept your local copy of Micro-RTSP defined: https://github.com/geeksville/TenDollarWebcam/blob/master/platformio.ini#L17

Also, the auto Wifi provisioning didn't work for me. I did not dig into it deeper as to why it wasn't showing up in my list of Wifi networks, I just reverted the changes back to use the wifikeys.h file for now.

Other wise, works great.

**Comment by ZhuDaHai** [comment]
What's this line supposed to be?
`file:///home/kevinh/development/devcam/Micro-RTSP`
I tried:
https://github.com/geeksville/Micro-RTSP.git
But it wants me to install a 'Git Client' or something. 
I don't get it. For what's supposed to be an easy 4 step install, this sure is a mess..

**Comment by kickbutts** [comment]
Auto Wifi provisioning did not work for me either. None of my devices was able to maintain a stable connection. I was not able to submit the Wifi credentials.
I also used the older version with wifikeys.h and it worked for me.

**Comment by jschefflervidscale** [comment]
Ditto on Wifi provisioning.
Project builds and installs successfully, though, so I will try using the older version. (which git SHA are folks using for that?)

**Comment by StripeyType** [comment]
Ditto AutoWifi provisioning not working, but I think I'm having bigger problems, as after flashing a brand-new device, I get nothing on OLED, nothing on WiFi, even when I build from 6046aaa and populate wifikeys.h

I'll keep banging my head against this tomorrow, and check back when you post new commits. Thanks!

**Comment by francistheodorecatte** [comment]
I got AutoWifi provisioning working with the Espressif EspTouch iOS app on my iPhone 6s running iOS 12.1.4, and the IoT Smartconfig app running on my Nexus 7 tablet running Android 6.0.1. Tried on two different wireless networks on completely different networking hardware without any issues (other than the one described below.)

I'm using the latest commit, 7c0dfa3, on my TTGO T-Camera board, and either a fresh flash or holding the switch labeled IO32 during bootup puts the board in pairing mode, where the OLED says: 
> Setup WiFi!

Bizarrely, EspTouch displays an error saying:
> **Execute Result**
> Esptouch fail

...but the ESP32 grabs an IP, and the OLED switches to showing the current DHCP address. IoT Smartconfig works as expected.

Soft resetting via the reset switch, or hard resets by pulling the USB cable don't cause the wireless config to be lost. I've only had to repair it after accidentally hitting the IO32 switch when resetting it.

**Comment by brahmafear** [comment]
No luck at all getting AutoWifi to work using latest git pull and iPhone8 with iOS11 running ESPtouch.  Board's OLED screen constantly says "SetupWifi" and app on phone reports fail.

**Comment by StripeyType** [comment]
I've revisited this with a new, tested, known-good cable and a fresh build.
I'm pleased to report that everything now works beautifully, including AutoWifi (though the maintainer of that lib recently has begun to recommend switching to https://github.com/Hieromon/AutoConnect, which apparently has better support for mixed 5/2.4 networks)
